### ISSUE TITLE
ExecJS SyntaxError: Expected identifier, string or number

### ISSUE THREAD

**Issue by sam596** [euphwes/pyTwistyScrambler#3]
While running for the first time I get this error:

```
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyTwistyScrambler import scrambler333
>>> scrambler333.get_WCA_scramble()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\spend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyTwistyScrambler\__init__.py", line 8, in trimmed_func
    return func(*args, **kwargs).strip()
  File "C:\Users\spend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyTwistyScrambler\scrambler333.py", line 8, in get_WCA_scramble
    return _333_SCRAMBLER.call("scramble_333.getRandomScramble")
  File "C:\Users\spend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\spend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\spend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\spend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\spend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Users\spend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: Expected identifier, string or number```

**Comment by qmayo** [comment]
Did you ever get it to work properly?

**Comment by Sargeanthost** [comment]
Same, I don't know whats wrong.

**Comment by Sargeanthost** [comment]
@qmayo  refer to the closed issue

**Comment by euphwes** [comment]
@qmayo @sam596 If you're still seeing this problem (after reinstalling node.js), can you please let me know the Python version and node.js version you have installed? I'll see if I can reproduce the problem locally and figure out where the Javascript syntax error is.

Some JS runtimes are more flexible than others with regards to syntax irregularities. It's probably just a stray semicolon or something that needs to be cleaned up in the underlying Javascript.

**Comment by qmayo** [comment]
I was able to fix it be re-installing node.
